# Generated by Django 4.2.7 on 2026-05-10 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_emailtemplate_builder_schema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_engine', '0001_initial'),
        ('organizations', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('list_added', 'Added To List'), ('list_removed', 'Removed From List'), ('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('email_bounced', 'Email Bounced'), ('unsubscribed', 'Unsubscribed'), ('complained', 'Complained'), ('custom', 'Custom')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactFieldDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL')], default='text', max_length=30)),
                ('options', models.JSONField(blank=True, default=list)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_visible_in_table', models.BooleanField(default=True)),
                ('is_importable', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ContactImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='pending', max_length=30)),
                ('error_report', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contactlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_type', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('suppressed', 'Suppressed')], db_index=True, default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='engagement_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='lifecycle_stage',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('lead_new', 'New Lead'), ('lead_warm', 'Warm Lead'), ('lead_hot', 'Hot Lead'), ('customer', 'Customer'), ('inactive', 'Inactive'), ('churn_risk', 'Churn Risk')], db_index=True, default='subscriber', max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='source_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='timezone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contact_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='filter_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='list_type',
            field=models.CharField(choices=[('static', 'Static List'), ('dynamic', 'Dynamic Segment'), ('suppression', 'Suppression List'), ('seed', 'Seed List')], default='static', max_length=30),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='total_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactlistmembership',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('source', 'Source'), ('lifecycle', 'Lifecycle'), ('interest', 'Interest'), ('behavior', 'Behavior'), ('campaign', 'Campaign'), ('suppression', 'Suppression'), ('value', 'Value'), ('geo', 'Geo'), ('custom', 'Custom')], default='custom', max_length=30),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactlistmembership',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='contactlistmembership',
            name='contact_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='contacts.contactlist'),
        ),
        migrations.AlterField(
            model_name='contacttag',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='contacttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='contacts.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='contactlist',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'consent_status'], name='contacts_co_organiz_c5d7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'lifecycle_stage'], name='contacts_co_organiz_e2fe93_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'lead_score'], name='contacts_co_organiz_d0849f_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'engagement_score'], name='contacts_co_organiz_44d7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'country'], name='contacts_co_organiz_dbf1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'source'], name='contacts_co_organiz_0885e5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_emailed_at'], name='contacts_co_last_em_159850_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_opened_at'], name='contacts_co_last_op_544777_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_clicked_at'], name='contacts_co_last_cl_4ee6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=models.Index(fields=['organization', 'list_type'], name='contacts_co_organiz_4e24c1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=models.Index(fields=['organization', 'is_active'], name='contacts_co_organiz_112148_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlistmembership',
            index=models.Index(fields=['contact', 'contact_list'], name='contacts_co_contact_e17b78_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlistmembership',
            index=models.Index(fields=['contact_list'], name='contacts_co_contact_652794_idx'),
        ),
        migrations.AddIndex(
            model_name='contacttag',
            index=models.Index(fields=['contact', 'tag'], name='contacts_co_contact_e7a10a_idx'),
        ),
        migrations.AddIndex(
            model_name='contacttag',
            index=models.Index(fields=['tag'], name='contacts_co_tag_id_7f4c29_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'slug'], name='contacts_ta_organiz_efc39d_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'tag_type'], name='contacts_ta_organiz_fa971a_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'is_active'], name='contacts_ta_organiz_fbdb1a_idx'),
        ),
        migrations.AddField(
            model_name='contactimportbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_import_batches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contactimportbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactfielddefinition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_field_definitions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contactactivity',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='contactactivity',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactactivity',
            name='email_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_engine.emailjob'),
        ),
        migrations.AddField(
            model_name='contactactivity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_activities', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='contactimportbatch',
            index=models.Index(fields=['organization', 'status'], name='contacts_co_organiz_e2c2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='contactimportbatch',
            index=models.Index(fields=['organization', 'created_at'], name='contacts_co_organiz_e9accf_idx'),
        ),
        migrations.AddIndex(
            model_name='contactfielddefinition',
            index=models.Index(fields=['organization', 'field_key'], name='contacts_co_organiz_b4d6be_idx'),
        ),
        migrations.AddIndex(
            model_name='contactfielddefinition',
            index=models.Index(fields=['organization', 'is_active'], name='contacts_co_organiz_705b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactfielddefinition',
            index=models.Index(fields=['organization', 'is_filterable'], name='contacts_co_organiz_481151_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactfielddefinition',
            unique_together={('organization', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='contactactivity',
            index=models.Index(fields=['organization', 'activity_type'], name='contacts_co_organiz_fb2843_idx'),
        ),
        migrations.AddIndex(
            model_name='contactactivity',
            index=models.Index(fields=['contact', 'activity_type'], name='contacts_co_contact_8f6deb_idx'),
        ),
        migrations.AddIndex(
            model_name='contactactivity',
            index=models.Index(fields=['contact', 'created_at'], name='contacts_co_contact_205821_idx'),
        ),
    ]
