# Generated by Django 4.2.7 on 2026-05-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_accent_color_and_more'),
        ('events', '0001_initial'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhookdelivery',
            name='webhooks_we_next_re_8ddc98_idx',
        ),
        migrations.AddField(
            model_name='webhook',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='retry_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='retry_delay',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.emailevent'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='event_type',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='response_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['created_at'], name='webhooks_we_created_9104e4_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['last_triggered_at'], name='webhooks_we_last_tr_80b361_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['organization', 'event_type'], name='webhooks_we_organiz_8a77ed_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['success', 'next_retry_at'], name='webhooks_we_success_147d71_idx'),
        ),
    ]
