# Generated by Django 4.2.7 on 2026-05-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed'), ('complained', 'Complained')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clicked_url', models.URLField(blank=True, max_length=2000)),
                ('email_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='email_engine.emailjob')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('redirect_url', models.URLField(max_length=500)),
                ('click_count', models.IntegerField(default=1)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='click_detail', to='events.emailevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['email_job', 'event_type'], name='events_emai_email_j_f3de7a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['timestamp'], name='events_emai_timesta_5fe907_idx'),
        ),
    ]
