# Generated by Django 4.2.7 on 2026-05-03 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('rate_limit_per_minute', models.IntegerField(default=10)),
                ('rate_limit_per_hour', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('login', 'Login Authentication'), ('register', 'Account Registration'), ('reset_password', 'Password Reset'), ('verify_email', 'Email Verification'), ('phone_verify', 'Phone Verification'), ('transaction', 'Transaction Confirmation'), ('custom', 'Custom Purpose')], default='login', max_length=50)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('request_count', models.IntegerField(default=0)),
                ('first_request_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code', 'is_used'], name='otp_otp_email_1e07a0_idx'), models.Index(fields=['phone', 'code', 'is_used'], name='otp_otp_phone_0fb72b_idx'), models.Index(fields=['expires_at'], name='otp_otp_expires_d5b803_idx'), models.Index(fields=['created_at'], name='otp_otp_created_441207_idx')],
            },
        ),
    ]
