# Generated by Django 4.2.7 on 2026-05-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_emailtemplate_builder_schema_and_more'),
        ('organizations', '0002_organization_accent_color_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignanalytics',
            name='clicked_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='generated_links',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='top_clicked_url',
            field=models.URLField(blank=True, default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='total_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='total_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='total_processing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='total_queued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='unique_click_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='unique_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='active_campaigns',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='clicked_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='email_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='emails_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='emails_queued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='generated_links',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='new_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='unique_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='webhook_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='webhook_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='total_bounces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='total_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='total_complaints',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='total_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='total_opens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='total_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='total_unsubscribes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='bounces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='emails_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='emails_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='opens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='unsubscribes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrganizationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_campaigns', models.PositiveIntegerField(default=0)),
                ('total_contacts', models.PositiveIntegerField(default=0)),
                ('total_email_jobs', models.PositiveIntegerField(default=0)),
                ('total_emails_sent', models.PositiveIntegerField(default=0)),
                ('total_emails_failed', models.PositiveIntegerField(default=0)),
                ('total_emails_queued', models.PositiveIntegerField(default=0)),
                ('total_generated_links', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_unique_clicks', models.PositiveIntegerField(default=0)),
                ('total_clicked_contacts', models.PositiveIntegerField(default=0)),
                ('total_webhook_deliveries', models.PositiveIntegerField(default=0)),
                ('total_webhook_success', models.PositiveIntegerField(default=0)),
                ('total_webhook_failures', models.PositiveIntegerField(default=0)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization Analytics',
            },
        ),
        migrations.CreateModel(
            name='LinkAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(max_length=1200)),
                ('generated_links', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('clicked_contacts', models.PositiveIntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_analytics', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_analytics', to='organizations.organization')),
            ],
            options={
                'ordering': ['-total_clicks', '-last_clicked_at'],
                'indexes': [models.Index(fields=['organization', 'campaign'], name='analytics_l_organiz_f807b0_idx'), models.Index(fields=['organization', 'original_url'], name='analytics_l_organiz_fcc507_idx'), models.Index(fields=['last_clicked_at'], name='analytics_l_last_cl_8131e2_idx')],
                'unique_together': {('organization', 'campaign', 'original_url')},
            },
        ),
    ]
