# Generated by Django 4.2.7 on 2026-05-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.CharField(choices=[('bounce', 'Hard Bounce'), ('complaint', 'Spam Complaint'), ('unsubscribe', 'Manual Unsubscribe'), ('manual', 'Manual Addition')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'email'], name='suppression_organiz_08d2f1_idx'), models.Index(fields=['created_at'], name='suppression_created_e6e898_idx')],
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
