# Generated by Django 4.2.7 on 2026-05-10 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accent_color',
            field=models.CharField(default='#10b981', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='advanced_segmentation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_features_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='automation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='button_style',
            field=models.CharField(default='rounded', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_schema_preset',
            field=models.CharField(default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom_branding_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_campaign_language',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_disclaimer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_email_theme',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_footer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_footer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_header_logo_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_reply_to_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_template_width',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='organization',
            name='double_opt_in_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='organization/favicons/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='font_family',
            field=models.CharField(default='Inter', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='gdpr_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('gym', 'Gym'), ('education', 'Education'), ('visa_consultant', 'Visa Consultant'), ('ecommerce', 'Ecommerce'), ('online_course', 'Online Course'), ('agency', 'Agency'), ('saas', 'SaaS')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='marketing_consent_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_contacts',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_segments',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_templates',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='organization',
            name='physical_address_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='preset_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='preset_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='tiktok_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Asia/Dhaka', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='unsubscribe_policy',
            field=models.CharField(choices=[('one_click', 'One Click'), ('confirmation', 'Confirmation Page'), ('preference_center', 'Preference Center')], default='one_click', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='webhooks_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_organization_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('marketer', 'Marketer'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subdomain'], name='organizatio_subdoma_179801_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['plan', 'is_active'], name='organizatio_plan_570b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry_type'], name='organizatio_industr_e197da_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_687988_idx'),
        ),
    ]
