# Generated by Django 4.2.7 on 2026-05-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField()),
                ('use_tls', models.BooleanField(default=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('smtp_type', models.CharField(choices=[('brevo', 'Brevo'), ('gmail', 'Gmail'), ('ses', 'Amazon SES'), ('sendgrid', 'SendGrid'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('daily_limit', models.IntegerField(default=0, help_text='Max emails per day (0 = unlimited)')),
                ('hourly_limit', models.IntegerField(default=0, help_text='Max emails per hour')),
                ('sent_today', models.IntegerField(default=0)),
                ('sent_this_hour', models.IntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(auto_now_add=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('health_score', models.FloatField(default=100.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='EmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('campaign', 'Marketing Campaign'), ('transactional', 'Transactional (Invoice, Receipt)'), ('otp', 'OTP / Verification'), ('notification', 'System Notification'), ('custom', 'Custom Email')], default='campaign', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject_snapshot', models.CharField(max_length=255)),
                ('body_snapshot', models.TextField()),
                ('html_body', models.TextField(blank=True)),
                ('otp_code', models.CharField(blank=True, max_length=10)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('use_custom_smtp', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('custom_smtp_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_engine.smtpconfig')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['-priority', 'scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smtpconfig',
            index=models.Index(fields=['organization', 'is_active'], name='email_engin_organiz_81e066_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpconfig',
            index=models.Index(fields=['organization', 'is_default'], name='email_engin_organiz_5666ee_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpconfig',
            index=models.Index(fields=['smtp_type'], name='email_engin_smtp_ty_d6f016_idx'),
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['status', 'priority', 'scheduled_at'], name='email_engin_status_cbf602_idx'),
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['campaign', 'status'], name='email_engin_campaig_11dd16_idx'),
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['email_type', 'status'], name='email_engin_email_t_f9ba8c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['otp_code', 'otp_expires_at'], name='email_engin_otp_cod_6b9683_idx'),
        ),
    ]
