# Generated by Django 4.2.7 on 2026-05-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_accent_color_and_more'),
        ('email_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='started', max_length=20)),
                ('response_message', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='smtpconfig',
            options={'ordering': ['priority', '-health_score', 'sent_today']},
        ),
        migrations.AddField(
            model_name='emailjob',
            name='last_smtp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_used_jobs', to='email_engine.smtpconfig'),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='allowed_email_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='last_hourly_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='last_minute_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='last_test_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='last_test_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='last_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='max_failures_before_cooldown',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='minute_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='reply_to_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='sent_this_minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailjob',
            name='body_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emailjob',
            name='email_type',
            field=models.CharField(choices=[('campaign', 'Marketing Campaign'), ('transactional', 'Transactional'), ('otp', 'OTP / Verification'), ('notification', 'System Notification'), ('custom', 'Custom Email')], default='campaign', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='daily_limit',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='hourly_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='priority',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='sent_this_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='sent_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['organization', 'status'], name='email_engin_organiz_d7cf01_idx'),
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['next_retry_at'], name='email_engin_next_re_487e41_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpconfig',
            index=models.Index(fields=['organization', 'priority'], name='email_engin_organiz_aeb06e_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpconfig',
            index=models.Index(fields=['cooldown_until'], name='email_engin_cooldow_3e78f3_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpconfig',
            index=models.Index(fields=['health_score'], name='email_engin_health__b85eea_idx'),
        ),
        migrations.AddField(
            model_name='smtpdeliveryattempt',
            name='email_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='email_engine.emailjob'),
        ),
        migrations.AddField(
            model_name='smtpdeliveryattempt',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='smtpdeliveryattempt',
            name='smtp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attempts', to='email_engine.smtpconfig'),
        ),
        migrations.AddIndex(
            model_name='smtpdeliveryattempt',
            index=models.Index(fields=['organization', 'status'], name='email_engin_organiz_60c76d_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpdeliveryattempt',
            index=models.Index(fields=['email_job', 'attempt_number'], name='email_engin_email_j_6b060b_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpdeliveryattempt',
            index=models.Index(fields=['smtp_config', 'status'], name='email_engin_smtp_co_16640b_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpdeliveryattempt',
            index=models.Index(fields=['created_at'], name='email_engin_created_46cbbb_idx'),
        ),
    ]
