# Generated by Django 4.2.7 on 2026-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_engine', '0002_smtpdeliveryattempt_alter_smtpconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailjob',
            name='links_processed',
            field=models.BooleanField(default=False),
        ),
    ]
