# Generated by Django 4.2.7 on 2026-05-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('marketing', 'Marketing Campaign'), ('transactional', 'Transactional Email'), ('otp', 'OTP / Verification'), ('welcome', 'Welcome Email'), ('newsletter', 'Newsletter'), ('custom', 'Custom Template')], default='marketing', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list, help_text='Example: ["first_name", "company_name", "reset_link"]')),
                ('preview_data', models.JSONField(blank=True, default=dict, help_text='Sample data for preview')),
                ('is_default', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('custom_html_content', models.TextField(blank=True)),
                ('custom_text_content', models.TextField(blank=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_opens', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_bounces', models.IntegerField(default=0)),
                ('total_unsubscribes', models.IntegerField(default=0)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('is_ab_test', models.BooleanField(default=False)),
                ('ab_variant_b', models.TextField(blank=True)),
                ('ab_winner_criteria', models.CharField(blank=True, choices=[('opens', 'Open Rate'), ('clicks', 'Click Rate')], max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.organization')),
                ('target_lists', models.ManyToManyField(blank=True, related_name='campaigns', to='contacts.contactlist')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.emailtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['organization', 'status'], name='campaigns_e_organiz_41ee6c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['organization', 'template_type'], name='campaigns_e_organiz_3c12b5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['is_default'], name='campaigns_e_is_defa_0afdfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('organization', 'name')},
        ),
    ]
