# Generated by Django 4.2.7 on 2026-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='builder_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Visual drag-and-drop email builder schema'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='preview_data',
            field=models.JSONField(blank=True, default=dict, help_text='Sample data used for live preview rendering'),
        ),
    ]
