# Generated by Django 4.2.7 on 2026-05-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('form_submitted', 'Form Submitted'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('tag_added', 'Tag Added'), ('date_based', 'Date Based'), ('list_joined', 'List Joined')], max_length=50)),
                ('trigger_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('send_email', 'Send Email'), ('wait', 'Wait/Delay'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('add_to_list', 'Add to List'), ('remove_from_list', 'Remove from List'), ('webhook', 'Webhook'), ('condition', 'Condition/Split')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.automation')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('automation', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['organization', 'is_active'], name='automation__organiz_e01587_idx'),
        ),
    ]
