# Generated by Django 4.2.7 on 2026-05-13 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_engine', '0002_smtpdeliveryattempt_alter_smtpconfig_options_and_more'),
        ('organizations', '0002_organization_accent_color_and_more'),
        ('contacts', '0002_contactactivity_contactfielddefinition_and_more'),
        ('campaigns', '0002_emailtemplate_builder_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('original_url', models.URLField(max_length=1200)),
                ('tracking_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('unique_click_count', models.PositiveIntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_links', to='campaigns.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_links', to='contacts.contact')),
                ('email_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_links', to='email_engine.emailjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_links', to='campaigns.emailtemplate')),
            ],
            options={
                'ordering': ['-last_clicked_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.TextField(blank=True, default='')),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('is_unique', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='campaigns.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='contacts.contact')),
                ('email_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='email_engine.emailjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='organizations.organization')),
                ('tracked_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.trackedlink')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['organization', 'is_active'], name='links_track_organiz_cb919a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['tracking_code'], name='links_track_trackin_ca9314_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['campaign'], name='links_track_campaig_597951_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['email_job'], name='links_track_email_j_20999e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['contact'], name='links_track_contact_807661_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['last_clicked_at'], name='links_track_last_cl_04dae4_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['organization', 'clicked_at'], name='links_linkc_organiz_fafb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['tracked_link', 'clicked_at'], name='links_linkc_tracked_cb870e_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['campaign', 'clicked_at'], name='links_linkc_campaig_4cac38_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['email_job'], name='links_linkc_email_j_cd41ab_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['contact'], name='links_linkc_contact_c0e1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['is_unique'], name='links_linkc_is_uniq_ed84a2_idx'),
        ),
    ]
